name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
       node-version: '16'
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # architecture: 'x64'

    - name: Setup pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-3.10-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.10-

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
    - name: Setup yarn cache
      uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Install dependencies
      run: python3 -m pip install -U jupyterlab~=3.0 jupyter_packaging~=0.7.9
    - name: Build the extension
      run: |
        jlpm
        jlpm run eslint:check
        python3 -m pip install .

        jupyter labextension list 2>&1 | grep -ie "jupyterlab-logout.*OK"
        python3 -m jupyterlab.browser_check
